MASTER_ADDRESS:
  host: "127.0.0.1"
  port: 3601
  dataPort: 7788
  logPort: 8888
WORKER_NAME: JOB
REPO_URL: ~/Codebase/trivial
PROJECT_NAME: trivial
FRAG_DIR: ./Frags
POST_DIR: ./Post
BUILD_DIR: ./Builds
