MASTER_ADDRESS:
  host: "127.0.0.1"
  port: 30001
  dataPort: 8899
  logPort: 8900

MERGER_ADDRESS:
  host: "127.0.0.1"
  port: 8025
  dataPort: 8030

WORKER_NAME: WORKER_EXAMPLE_1

REPO_URL: git@127.0.0.1:root/try.git

STORAGE: DoneStorage

PROJECT_NAME: try

QUEUE_SIZE: 1024

MAX_TASK_CAN_PROC: 1

PROCESS_POOL_SIZE: 1

RESULT_PATH: ./BSP/config/image/link/pack.rar

PostStorage: ./PostStorage

BUILDING_CMDS:
  - sleep 60

ROLE: NORMAL

FRAG_DIR: ./Frags
POST_DIR: ./Post
BUILD_DIR: ./Build1
